apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-directory-deployment
  labels:
    app: ai-directory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-directory
  template:
    metadata:
      labels:
        app: ai-directory
    spec:
      containers:
      - name: ai-directory-container
        image: docker.io/impara1/ai-directory-image:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ai-directory-service
spec:
  type: LoadBalancer
  selector:
    app: ai-directory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
